name: ExatoLP Web - Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: .
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Fetch build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
    - name: Test
      run: dotnet test --no-build --verbosity normal
