name: ExatoLP Web - Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.0.0
      with:
        name: build-artifacts
        path: .
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Fetch build artifacts
      uses: actions/download-artifact@v4.1.1
      with:
        name: build-artifacts
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test --no-build --verbosity normal
